### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by hailey99** [hailey99/hailey99.github.io#2]
- [ ] Organize CSS and classes which are used repeatedly
- [ ] create 'Scroll up' button 
- [ ] Add the.. what is it called 탭 옆에 붙는 로고 ㅋㅋㅋ 붙이기
- [ ]

**Comment by hailey99** [comment]
**Calendar**
- [ ] 클릭된 year css 적용하기

**Comment by hailey99** [comment]
**Keep it Simple**
- [ ] 가장 중요한 몇개의 프로젝트만 넣고 글도 최소한으로
- [ ] 가장 중요한 프로젝트를 맨 위에
- [ ] 바로 라이브 프로젝트를 볼 수 있는 버튼을 만들어 직접 들어가볼 수 있도록
- [ ] 위 프로젝트를 깃허브에 올리고 코드도 즉시 볼수 있도록 링크
- [ ] 3-6개의 최고 프로젝트만 넣기
- [ ] 강의, 튜토리얼 따라한 걸 그대로 넣지말고 커스터마이징
- [ ] 이메일, 핸드폰번호를 Navigation bar, About page, Contact section에
- [ ] 여러 다른 플랫폼에 같은 프로필 이미지 사용할 것 
- [ ] primary color 일관되도록
- [ ] 밑줄 css 효과 추가

**Comment by hailey99** [comment]
- [ ] post markdown 으로 갈아타기~
